### ISSUE TITLE
Auto closes

### ISSUE THREAD

**Issue by IRetr0I** [MrStark-XD/Edu-Mail-Generator#11]
When i run the bot.py, the chrome auto closes after like 1-3 sec. I tried firefox too but im seeing a white page on that

**Comment by shoyrock** [comment]
> When i run the bot.py, the chrome auto closes after like 1-3 sec. I tried firefox too but im seeing a white page on that

same did you ever find a fix?

**Comment by amrfateem** [comment]
Same

**Comment by IRetr0I** [comment]
> > When i run the bot.py, the chrome auto closes after like 1-3 sec. I tried firefox too but im seeing a white page on that
> 
> same did you ever find a fix?

no

**Comment by chmohsin** [comment]
please solve auto solve problem

**Comment by kabanla101** [comment]
*] Performing Incapsula Bypass
[*] Fetching Token (success)
[*] Fetching Cookies (success)
[*] Sending Custom Fields and Token to Server (success)
[*] Setting Incap Token (success)
[*] Sending Custom Cookies (success)
[*] Parsing Incap Cookies (success)
[*] Interceptor Addition (success)
[*] Injecting Incap CookiesTraceback (most recent call last):
  File "/home/fola/Tools/Edu-Mail-Generator-main/bot.py", line 1169, in <module>
    main()
  File "/home/fola/Tools/Edu-Mail-Generator-main/bot.py", line 1166, in main
    start_bot(start_url, userEmail, allColleges[userInput], userInput + 1, cookies, token)
  File "/home/fola/Tools/Edu-Mail-Generator-main/bot.py", line 98, in start_bot
    driver.add_cookie(ck)
  File "/home/fola/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1131, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "/home/fola/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/home/fola/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=100.0.4896.127)
Stacktrace:
#0 0x55bd43e7ead3 <unknown>
#1 0x55bd43bde568 <unknown>
#2 0x55bd43c56446 <unknown>
#3 0x55bd43c325f2 <unknown>
#4 0x55bd43c45824 <unknown>
#5 0x55bd43c324e3 <unknown>
#6 0x55bd43c07d1a <unknown>
#7 0x55bd43c08e75 <unknown>
#8 0x55bd43eacefd <unknown>
#9 0x55bd43ec619b <unknown>
#10 0x55bd43eaec65 <unknown>
#11 0x55bd43ec6ec8 <unknown>
#12 0x55bd43ea2360 <unknown>
#13 0x55bd43ee2a68 <unknown>
#14 0x55bd43ee2be8 <unknown>
#15 0x55bd43efc7fd <unknown>
#16 0x7fc0e6f9cd80 <unknown>

**Comment by FORMYBOTAM** [comment]
I GOT THIS ERROR HAS ANYONE FIXED IT
[*] Injecting Incap CookiesTraceback (most recent call last):
  File "B:\WINDOWS\DOWNLOADS\LAERY\Edu-Mail-Generator-main\Edu-Mail-Generator-main\bot.py", line 1169, in <module>
    main()
  File "B:\WINDOWS\DOWNLOADS\LAERY\Edu-Mail-Generator-main\Edu-Mail-Generator-main\bot.py", line 1166, in main
    start_bot(start_url, userEmail, allColleges[userInput], userInput + 1, cookies, token)
  File "B:\WINDOWS\DOWNLOADS\LAERY\Edu-Mail-Generator-main\Edu-Mail-Generator-main\bot.py", line 98, in start_bot
    driver.add_cookie(ck)
  File "B:\WINDOWS\PROGRAMS\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1136, in add_cookie
    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
  File "B:\WINDOWS\PROGRAMS\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "B:\WINDOWS\PROGRAMS\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=102.0.5005.63)
Stacktrace:
Backtrace:
        Ordinal0 [0x0059D953+2414931]
        Ordinal0 [0x0052F5E1+1963489]
        Ordinal0 [0x0041C6B8+837304]
        Ordinal0 [0x00483191+1257873]
        Ordinal0 [0x0046449C+1131676]
        Ordinal0 [0x00474812+1198098]
        Ordinal0 [0x004642B6+1131190]
        Ordinal0 [0x0043E860+976992]
        Ordinal0 [0x0043F756+980822]
        GetHandleVerifier [0x0080CC62+2510274]
        GetHandleVerifier [0x007FF760+2455744]
        GetHandleVerifier [0x0062EABA+551962]
        GetHandleVerifier [0x0062D916+547446]
        Ordinal0 [0x00535F3B+1990459]
        Ordinal0 [0x0053A898+2009240]
        Ordinal0 [0x0053A985+2009477]
        Ordinal0 [0x00543AD1+2046673]
        BaseThreadInitThunk [0x7600FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77BF7A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77BF7A4E+238]

**Comment by yezysarered** [comment]
please MAKE A NEW ISSUE GUYS
