### ISSUE TITLE
Session issue? Does not work for any browser option or college selection.

### ISSUE THREAD

**Issue by klrmac** [MrStark-XD/Edu-Mail-Generator#12]
[] Setting Incap Token (success)
[] Sending Custom Cookies (success)
[] Parsing Incap Cookies (success)
[] Interceptor Addition (success)
[*] Injecting Incap CookiesTraceback (most recent call last):
File "/home/fola/Tools/Edu-Mail-Generator-main/bot.py", line 1169, in
main()
File "/home/fola/Tools/Edu-Mail-Generator-main/bot.py", line 1166, in main
start_bot(start_url, userEmail, allColleges[userInput], userInput + 1, cookies, token)
File "/home/fola/Tools/Edu-Mail-Generator-main/bot.py", line 98, in start_bot
driver.add_cookie(ck)
File "/home/fola/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 1131, in add_cookie
self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})
File "/home/fola/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
self.error_handler.check_response(response)
File "/home/fola/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
(Session info: chrome=100.0.4896.127)

**Comment by laimumu** [comment]
i get the same error nobody to can solve it?
