### ISSUE TITLE
Error - Run setup.py first

### ISSUE THREAD

**Issue by xhendev** [MrStark-XD/Edu-Mail-Generator#6]
It doesnt work. I ran setup.py so much times. 

```
PS C:\Users\<Username>\Desktop\Edu-Mail-Generator-main> py setup.py
Requirement already satisfied: requests in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (2.26.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from requests) (2.0.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from requests) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from requests) (1.26.7)
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\<Username>\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


Requirement already satisfied: clint in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (0.5.1)
Requirement already satisfied: args in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from clint) (0.1.0)
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\<Username>\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


Requirement already satisfied: faker in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (9.8.0)
Requirement already satisfied: python-dateutil>=2.4 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from faker) (2.8.2)
Requirement already satisfied: text-unidecode==1.3 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from faker) (1.3)
Requirement already satisfied: six>=1.5 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.4->faker) (1.16.0)
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\<Username>\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


Requirement already satisfied: selenium in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (4.0.0b4)
Requirement already satisfied: urllib3[secure]~=1.26 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from selenium) (1.26.7)
Requirement already satisfied: trio~=0.17 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from selenium) (0.19.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: attrs>=19.2.0 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium) (21.2.0)
Requirement already satisfied: outcome in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: cffi>=1.14 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: sortedcontainers in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: sniffio in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: idna in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: pycparser in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from trio-websocket~=0.9->selenium) (1.0.0)
Requirement already satisfied: certifi in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from urllib3[secure]~=1.26->selenium) (2021.10.8)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from urllib3[secure]~=1.26->selenium) (35.0.0)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from urllib3[secure]~=1.26->selenium) (21.0.0)
Requirement already satisfied: six>=1.5.2 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure]~=1.26->selenium) (1.16.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.12.0)
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\<Username>\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


Requirement already satisfied: colorama in c:\users\<Username>\appdata\local\programs\python\python310\lib\site-packages (0.4.4)
WARNING: You are using pip version 21.2.3; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\<Username>\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


Firefox
Installed verision - 94.0.1
Latest geckodriver version - v0.30.0
Downloading...
Traceback (most recent call last):
  File "C:\Users\<Username>\Desktop\Edu-Mail-Generator-main\setup.py", line 70, in <module>
    main()
  File "C:\Users\<Username>\Desktop\Edu-Mail-Generator-main\setup.py", line 29, in main
    setup_Firefox(firefox_ver)
  File "C:\Users\<Username>\Desktop\Edu-Mail-Generator-main\__dwnldDrivers\versions.py", line 241, in setup_Firefox
    dwnld_zip_file(dwnldLink, './webdriver')
  File "C:\Users\<Username>\Desktop\Edu-Mail-Generator-main\__dwnldDrivers\versions.py", line 188, in dwnld_zip_file
    with ZipFile(BytesIO(r.content)) as my_zip_file:
  File "C:\Users\<Username>\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "C:\Users\<Username>\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
PS C:\Users\<Username>\Desktop\Edu-Mail-Generator-main>
```

**Comment by sailingwithsandeep** [comment]
yes i am having same error

**Comment by MrStark-XD** [comment]
Now fixed

**Comment by xhendrikg** [comment]
Its still not working!
